# syntax=docker/dockerfile:1
FROM node:18-alpine AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
# Build using only this app's files
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig*.json ./
COPY index.html ./
COPY public ./public
COPY src ./src
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
